learning_rate: 5.e-5
batch_size: 8
input_size: 256
epoch: 10

dataset: "E:/Dataset/CMU/hand_syn/synth1"
checkpoint: "hourglass/checkpoints/testdef.chk"
save_model: True
load_model: False

model: "hourglass_def"
output_type: "heatmap"

report: "hourglass/reports/hrdef/"