learning_rate: 5.e-5
batch_size: 4
input_size: 256
epoch: 10

dataset: "E:/Dataset/CMU/hand_manual/manual_train"
checkpoint: "hourglass/checkpoints/testdef_6hm.chk"
save_model: True
load_model: True

model: "hourglass_def"
output_type: "heatmap"

report: "hourglass/reports/hrdef6hm/"