learning_rate: 4.e-2
batch_size: 2
input_size: 128
epoch: 10

dataset: "E:/Dataset/CMU/hand_syn/synth1"
checkpoint: "homebrew/checkpoints/test.chk"
save_model: True
load_model: False

model: "homebrew"
output_type: "keypoints"

report: "homebrew/reports"