learning_rate: 1.e-5
batch_size: 8
input_size: 256
epoch: 10

dataset: "E:/Dataset/RHD_published_v2/training/"
checkpoint: "handSegment/lightning_logs/version_0/checkpoints/epoch=1-step=10316.ckpt"
save_model: True
load_model: False

model: "FPN"
output_type: "light_segment"

report: "colorHandPose/reports/cf1_RHD/"