learning_rate: 4.e-2
batch_size: 8
input_size: 256
epoch: 100

dataset: "E:/Dataset/CMU/hand_manual/manual_train"
checkpoint: "colorHandPose/checkpoints/posenet.pth.tar"
save_model: False
load_model: False

model: "colorHandPose_postNet"
output_type: "heatmap"

report: "colorHandPose/reports/posenet/"