learning_rate: 4.e-2
batch_size: 32
input_size: 256
epoch: 100

dataset: "E:/HandPose/CMU/hand_manual/manual_train"
checkpoint: "colorHandPose/checkpoints/posenet.pth.tar"
save_model: False
load_model: False

output_type: "heatmap"