learning_rate: 1.e-5
batch_size: 8
input_size: 256
epoch: 1

dataset: "E:/Dataset/CMU/hand_manual/manual_train/"
checkpoint: "colorHandPose/checkpoints/segment_cf01_CMU.pth.tar"
save_model: True
load_model: False

model: "colorHandPose_handSeg"
output_type: "segment"

report: "colorHandPose/reports/cf1_CMU/"