learning_rate: 5.e-5
batch_size: 8
input_size: 256
epoch: 10

dataset: "E:/Dataset/RHD_published_v2/training/"
checkpoint: "colorHandPose/checkpoints/segment_cf01_RHD.pth.tar"
save_model: True
load_model: True

model: "colorHandPose_handSeg"
output_type: "segment_RHD"

report: "colorHandPose/reports/cf1_RHD/"